export const ACTIONS = {

    MOVIES: {
        ADD_MOVIE: "ADD_MOVIE",
        ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
        GET_FROM_SERVER_DONE: "GET_FROM_SERVER_DONE",
        GET_MOVIE_DETAILS_DONE: "GET_MOVIE_DETAILS_DONE",
        IS_CURRENT_MOVIE_LOADING: "IS_CURRENT_MOVIE_LOADING"
    }

}